### ISSUE TITLE
PSTR within templated code

### ISSUE THREAD

**Issue by mikee47** [earlephilhower/newlib-xtensa#4]
GCC silently disregards attributes in templated code (https://github.com/esp8266/Arduino/pull/6294#issuecomment-560576979)

Test case:

```
template <typename T>
void templateTest(T x)
{
	Serial.print("x = ");
	Serial.println(x);
	Serial.println(PSTR("This text ends up in RAM (.rodata) because GCC silently disregards attributes in templated code."));
}
```

This can be fixed by adding to linker script .irom0.text output section:

```
	/* Inline flash strings PSTR() within templated code */
	*(.rodata._ZZ*__c)
	*(.rodata._ZZ*__c_*)
```

With this in mind, a safer/more descriptive name than `__c` would be preferable, such as `__pstr__`.

**Comment by mikee47** [comment]
Further thought. The above linker script changes would also catch regular PSTR usage, which means PROGMEM doesn't need to be applied to it. That would emit it to the regular `.rodata` section and be coalesced automatically before the linker moves it into .irom0.text.

Filter can be simplified to: `*(.rodata.*__pstr__*)` or just `*(*__pstr__*)`

**Comment by earlephilhower** [comment]
With the new PSTR macros, we're already placing every string into a single block of dedupable strings by the section name itself.  That is, on the Arduino core, we don't have the lines you mentioned above.  Everything is done w/no chance of naming conflict by the ` *(.irom0.pstr.*)` line.

I think if you use the macro as-defined here and not the older one you've got in Sming, it may actually take care of the template stuff, too, since the assembly emitted itself is making the `.section XXXX` in the intermediate .S file, not GCC or its template munger.

**Comment by mikee47** [comment]
This is the intermediate assembly generated for the above test case:

```
	.weak	_ZZ12templateTestIiEvT_E8__pstr__
	.section	.rodata._ZZ12templateTestIiEvT_E8__pstr__,"aG",@progbits,_ZZ12templateTestIiEvT_E8__pstr__,comdat
	.align	4
	.type	_ZZ12templateTestIiEvT_E8__pstr__, @object
	.size	_ZZ12templateTestIiEvT_E8__pstr__, 92
_ZZ12templateTestIiEvT_E8__pstr__:
	.string	"This PSTR text ends up in RAM because GCC silently disregards attributes in templated code."
```

**Comment by mikee47** [comment]
With a regular (non-templated) function, I get this:

```
	.section	".irom0.pstr.test-string.cpp.17.155", "aSM", @progbits, 1 #,"a"
	.align	4
	.type	_ZZ15nonTemplateTestiE8__pstr__, @object
	.size	_ZZ15nonTemplateTestiE8__pstr__, 66
_ZZ15nonTemplateTestiE8__pstr__:
	.string	"This PSTR text is stored correctly as it's not in templated code."
```

**Comment by mikee47** [comment]
This is a known issue with GCC and templates. https://answers.launchpad.net/gcc-arm-embedded/+question/615576

> The problem with using attributes and templates is overloading. Because attributes don't mangle var names, overloading becomes problematic in C++. I'm guessing thats why the section attribute on a template var is ignored. See some notes here - https://gcc.gnu.org/onlinedocs/gcc/Attribute-Syntax.html.

**Comment by mikee47** [comment]
Another PROGMEM related issue I've noticed with the new compiler is that it doesn't always tag use of `__PRETTY_FUNCTION__` such as used within `assert()`. This means they cannot be filtered out (by section or by name) and thus consume RAM. Example with the 'old' toolchain:

```
.LFE5436:
	.size	_ZZ13registerGroupI17ArduinoStringTestEvvENUlvE_4_FUNEv, .-_ZZ13registerGroupI17ArduinoStringTestEvvENUlvE_4_FUNEv
	.section	.rodata._ZZN17ArduinoStringTest7executeEvE19__PRETTY_FUNCTION__,"a",@progbits
	.type	_ZZN17ArduinoStringTest7executeEvE19__PRETTY_FUNCTION__, @object
	.size	_ZZN17ArduinoStringTest7executeEvE19__PRETTY_FUNCTION__, 42
_ZZN17ArduinoStringTest7executeEvE19__PRETTY_FUNCTION__:
	.string	"virtual void ArduinoStringTest::execute()"
```

The new toolchain produces this:

```
.LC24:
	.string	"virtual void ArduinoStringTest::execute()"

// ... further down

	.section	.text._ZN17ArduinoStringTest7executeEv,"axG",@progbits,_ZN17ArduinoStringTest7executeEv,comdat
	.literal_position
	.literal .LC6, _ZZN17ArduinoStringTest7executeEvE8__pstr__
	.literal .LC8, .LC7
	.literal .LC9, _ZZN17ArduinoStringTest7executeEvE18__pstr__tmpExprStr
	.literal .LC11, .LC10
	.literal .LC12, _ZZN17ArduinoStringTest7executeEvE14__pstr__fmtbuf
	.literal .LC13, _ZZN17ArduinoStringTest7executeEvE8__pstr___2
	.literal .LC15, .LC14
	.literal .LC17, .LC16
	.literal .LC19, .LC18
	.literal .LC20, _ZZN17ArduinoStringTest7executeEvE18__pstr__tmpExprStr_0
	.literal .LC22, .LC21
	.literal .LC23, _ZZN17ArduinoStringTest7executeEvE14__pstr__fmtbuf_0
	.literal .LC25, .LC24 ///< Reference to above string
```

**Comment by earlephilhower** [comment]
Think this was taken care of in #3.  Since GCC drops the section hint, we have to match by name (now `__pstr__`).
